/**
 * Basic Module Template
 * Generated by OAMTM Evolve Engine
 */

export interface ModuleConfig {
  name: string;
  version: string;
  enabled: boolean;
}

export class BasicModule {
  private config: ModuleConfig;

  constructor(config: ModuleConfig) {
    this.config = config;
  }

  public initialize(): void {
    console.log(`Initializing module: ${this.config.name}`);
  }

  public getConfig(): ModuleConfig {
    return this.config;
  }
}

export default BasicModule;
