/**
 * OAMTM Auto-PR Creator
 * Erstellt automatisch Pull Requests für Evolve-Änderungen
 */
import { promises as fs } from 'fs';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

// interface _PRConfig {
//   title: string;
//   body: string;
//   head: string;
//   base: string;
//   labels: string[];
// }

interface EvolveResult {
  created: any[];
  manifest: any;
  health: boolean;
}

export async function createEvolvePR(result: EvolveResult): Promise<void> {
  if (result.created.length === 0) {
    console.log('[auto-pr] No changes to create PR for');
    return;
  }

  const branchName = `evolve-${Date.now().toString(36)}`;
  
  try {
    // Create new branch
    await execAsync(`git checkout -b ${branchName}`);
    
    // Add changes
    await execAsync('git add manifest.json audit/*.json audit/*.jsonl');
    
    // Commit changes
    const commitMessage = `chore(evolve): create ${result.created.length} new modules

Generated modules:
${result.created.map(c => `- ${c.id} (${c.where})`).join('\n')}

Health gates: ${result.health ? '✅ Passed' : '❌ Failed'}
Generated by: OAMTM Evolve Engine`;
    
    await execAsync(`git commit -m "${commitMessage}"`);
    
    // Push branch
    await execAsync(`git push -u origin ${branchName}`);
    
    console.log(`[auto-pr] Branch ${branchName} created and pushed`);
    console.log(`[auto-pr] Create PR manually: https://github.com/ViewunitySystem/OnAirMulTiMedia/compare/${branchName}`);
    
    // Log PR creation attempt
    const timestamp = new Date().toISOString();
    const logEntry = {
      ts: timestamp,
      rule: 'auto-pr',
      action: 'create-pr-branch',
      detail: {
        branch: branchName,
        modules: result.created,
        health: result.health
      }
    };

    await fs.mkdir('audit', { recursive: true });
    await fs.appendFile('audit/fixes.jsonl', JSON.stringify(logEntry) + '\n');
    
  } catch (error) {
    console.error('[auto-pr] Failed to create PR:', error);
    
    // Log failure
    const timestamp = new Date().toISOString();
    const logEntry = {
      ts: timestamp,
      rule: 'auto-pr',
      action: 'create-pr-failed',
      detail: {
        error: (error as Error).message,
        modules: result.created
      }
    };

    await fs.mkdir('audit', { recursive: true });
    await fs.appendFile('audit/fixes.jsonl', JSON.stringify(logEntry) + '\n');
  }
}

export async function checkPRRequirements(): Promise<boolean> {
  try {
    // Check if we're in a git repository
    await execAsync('git status');
    
    // Check if we have changes
    const { stdout } = await execAsync('git status --porcelain');
    return stdout.trim().length > 0;
    
  } catch (error) {
    console.error('[auto-pr] Git check failed:', error);
    return false;
  }
}

// CLI usage
if (import.meta.url === `file://${process.argv[1]}`) {
  const mockResult: EvolveResult = {
    created: [
      { id: 'test-module-123', where: 'modules', from: 'blueprints/module-basic' }
    ],
    manifest: { modules: [] },
    health: true
  };
  
  createEvolvePR(mockResult).catch(console.error);
}
