// OAMTM User Studio - Enhanced Testing & Optimization
// This file contains enhanced functionality for testing and optimization

class UserStudioTester {
  constructor() {
    this.testResults = [];
    this.performanceMetrics = {};
    this.init();
  }

  init() {
    this.setupEventListeners();
    this.startPerformanceMonitoring();
    this.setupErrorHandling();
  }

  setupEventListeners() {
    // Enhanced form validation
    document.getElementById('title')?.addEventListener('input', (e) => {
      this.validateTitle(e.target.value);
    });

    document.getElementById('desc')?.addEventListener('input', (e) => {
      this.validateDescription(e.target.value);
    });

    document.getElementById('code')?.addEventListener('input', (e) => {
      this.validateCode(e.target.value);
    });

    // Enhanced AI draft with better error handling
    document.getElementById('aiDraft')?.addEventListener('click', async () => {
      await this.enhancedAIDraft();
    });

    // Enhanced preview with error handling
    document.getElementById('preview')?.addEventListener('click', () => {
      this.enhancedPreview();
    });

    // Enhanced submit with validation
    document.getElementById('submit')?.addEventListener('click', async () => {
      await this.enhancedSubmit();
    });
  }

  validateTitle(title) {
    const minLength = 3;
    const maxLength = 120;
    const isValid = title.length >= minLength && title.length <= maxLength;
    
    this.updateFieldValidation('title', isValid, 
      isValid ? '' : `Titel muss zwischen ${minLength} und ${maxLength} Zeichen lang sein`);
    
    return isValid;
  }

  validateDescription(desc) {
    const minLength = 5;
    const maxLength = 2000;
    const isValid = desc.length >= minLength && desc.length <= maxLength;
    
    this.updateFieldValidation('desc', isValid,
      isValid ? '' : `Beschreibung muss zwischen ${minLength} und ${maxLength} Zeichen lang sein`);
    
    return isValid;
  }

  validateCode(code) {
    const minLength = 5;
    const maxLength = 200000;
    const isValid = code.length >= minLength && code.length <= maxLength;
    
    this.updateFieldValidation('code', isValid,
      isValid ? '' : `Code muss zwischen ${minLength} und ${maxLength} Zeichen lang sein`);
    
    return isValid;
  }

  updateFieldValidation(fieldId, isValid, message) {
    const field = document.getElementById(fieldId);
    if (!field) return;

    // Remove existing validation classes
    field.classList.remove('valid', 'invalid');
    
    // Add appropriate class
    field.classList.add(isValid ? 'valid' : 'invalid');
    
    // Update or create validation message
    let messageEl = field.parentNode.querySelector('.validation-message');
    if (!messageEl) {
      messageEl = document.createElement('div');
      messageEl.className = 'validation-message';
      field.parentNode.appendChild(messageEl);
    }
    
    messageEl.textContent = message;
    messageEl.className = `validation-message ${isValid ? 'success' : 'error'}`;
  }

  async enhancedAIDraft() {
    const title = document.getElementById('title').value.trim();
    const desc = document.getElementById('desc').value.trim();
    const target = document.getElementById('target').value;

    if (!this.validateTitle(title) || !this.validateDescription(desc)) {
      this.setStatus('Bitte korrigiere die Eingabefehler', 'error');
      return;
    }

    this.setStatus('AI generiert Vorschlag …', 'info');
    this.startLoading('aiDraft');

    try {
      const startTime = performance.now();
      
      // Simulate AI processing with realistic delay
      await new Promise(resolve => setTimeout(resolve, 1000 + Math.random() * 2000));
      
      const code = this.generateEnhancedAIDraft(title, desc, target);
      document.getElementById('code').value = code;
      
      const endTime = performance.now();
      this.performanceMetrics.aiDraftTime = endTime - startTime;
      
      this.setStatus('Vorschlag erstellt. Prüfe/ändere den Code und nutze Vorschau.', 'success');
      this.recordTestResult('aiDraft', true, `Generated in ${Math.round(endTime - startTime)}ms`);
      
    } catch (error) {
      this.setStatus('Fehler beim AI-Vorschlag: ' + error.message, 'error');
      this.recordTestResult('aiDraft', false, error.message);
    } finally {
      this.stopLoading('aiDraft');
    }
  }

  generateEnhancedAIDraft(title, desc, target) {
    const templates = {
      'modules/user/': `// ${title}
// ${desc}
// Generated by OAMTM User Studio

class UserModule {
  constructor() {
    this.name = '${title}';
    this.version = '1.0.0';
    this.description = '${desc}';
    this.created = new Date().toISOString();
  }

  init() {
    console.log('User Module ${title} initialized');
    this.setupEventListeners();
    this.loadConfiguration();
  }

  setupEventListeners() {
    // TODO: Implementiere deine Event-Handler hier
  }

  loadConfiguration() {
    // TODO: Lade Konfiguration aus localStorage oder API
  }

  render() {
    return \`
      <div class="user-module" data-module="\${this.name}">
        <header>
          <h3>\${this.name}</h3>
          <p>\${this.description}</p>
          <span class="version">v\${this.version}</span>
        </header>
        <main>
          <!-- Deine UI hier -->
        </main>
        <footer>
          <small>Erstellt: \${new Date(this.created).toLocaleDateString('de-DE')}</small>
        </footer>
      </div>
    \`;
  }

  // OAMTM Integration
  getManifest() {
    return {
      name: this.name,
      version: this.version,
      description: this.description,
      type: 'user-module',
      permissions: ['read', 'write'],
      created: this.created
    };
  }
}

// Export für OAMTM Integration
if (typeof module !== 'undefined' && module.exports) {
  module.exports = UserModule;
} else if (typeof window !== 'undefined') {
  window.UserModule = UserModule;
}`,

      'webui/components/': `// ${title} - Web Component
// ${desc}
// Generated by OAMTM User Studio

class ${title.replace(/[^a-zA-Z0-9]/g, '')}Component extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this.data = {};
  }

  static get observedAttributes() {
    return ['title', 'description'];
  }

  connectedCallback() {
    this.render();
    this.setupEventListeners();
  }

  attributeChangedCallback(name, oldValue, newValue) {
    if (oldValue !== newValue) {
      this.render();
    }
  }

  setupEventListeners() {
    // TODO: Implementiere deine Event-Handler hier
  }

  render() {
    this.shadowRoot.innerHTML = \`
      <style>
        :host {
          display: block;
          font-family: system-ui, -apple-system, sans-serif;
          --primary-color: #93c5fd;
          --background-color: #111827;
          --text-color: #e5e7eb;
        }
        .component {
          padding: 16px;
          border: 1px solid #1f2a52;
          border-radius: 8px;
          background: var(--background-color);
          color: var(--text-color);
        }
        .header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 12px;
        }
        .title {
          font-size: 1.2em;
          font-weight: 600;
          color: var(--primary-color);
        }
        .description {
          opacity: 0.8;
          font-size: 0.9em;
        }
      </style>
      <div class="component">
        <div class="header">
          <h3 class="title">\${this.getAttribute('title') || '${title}'}</h3>
        </div>
        <p class="description">\${this.getAttribute('description') || '${desc}'}</p>
        <!-- Deine Komponente hier -->
      </div>
    \`;
  }
}

// Registriere das Custom Element
customElements.define('${title.toLowerCase().replace(/[^a-z0-9]/g, '-')}-component', ${title.replace(/[^a-zA-Z0-9]/g, '')}Component);`,

      'apps/user/': `// ${title} - User App
// ${desc}
// Generated by OAMTM User Studio

class UserApp {
  constructor() {
    this.name = '${title}';
    this.description = '${desc}';
    this.version = '1.0.0';
    this.created = new Date().toISOString();
    this.state = {
      initialized: false,
      data: {},
      ui: null
    };
  }

  async init() {
    console.log('Initializing ${title}...');
    try {
      await this.loadData();
      await this.setupUI();
      this.state.initialized = true;
      this.emit('initialized');
    } catch (error) {
      console.error('Failed to initialize app:', error);
      this.emit('error', error);
    }
  }

  async loadData() {
    // TODO: Lade Daten aus API oder localStorage
    this.state.data = {};
  }

  async setupUI() {
    // TODO: Setup UI components
    this.state.ui = this.render();
  }

  render() {
    return \`
      <div class="user-app" data-app="\${this.name}">
        <header class="app-header">
          <h1>\${this.name}</h1>
          <p>\${this.description}</p>
          <div class="app-meta">
            <span class="version">v\${this.version}</span>
            <span class="created">\${new Date(this.created).toLocaleDateString('de-DE')}</span>
          </div>
        </header>
        <main class="app-main">
          <!-- Deine App-Logik hier -->
        </main>
        <footer class="app-footer">
          <small>OAMTM User App</small>
        </footer>
      </div>
    \`;
  }

  // Event system
  emit(event, data) {
    const customEvent = new CustomEvent(\`app-\${event}\`, { detail: data });
    document.dispatchEvent(customEvent);
  }

  // OAMTM Integration
  getManifest() {
    return {
      name: this.name,
      version: this.version,
      description: this.description,
      type: 'user-app',
      permissions: ['read', 'write'],
      created: this.created,
      state: this.state
    };
  }
}

// Export
if (typeof module !== 'undefined' && module.exports) {
  module.exports = UserApp;
} else if (typeof window !== 'undefined') {
  window.UserApp = UserApp;
}`
    };

    return templates[target] || `// ${title}
// ${desc}
// Generated by OAMTM User Studio

console.log('Feature: ${title}');
console.log('Description: ${desc}');

// TODO: Implementiere deine Logik hier
const ${title.replace(/[^a-zA-Z0-9]/g, '')} = {
  name: '${title}',
  description: '${desc}',
  version: '1.0.0',
  created: new Date().toISOString()
};

// Export
if (typeof module !== 'undefined' && module.exports) {
  module.exports = ${title.replace(/[^a-zA-Z0-9]/g, '')};
} else if (typeof window !== 'undefined') {
  window.${title.replace(/[^a-zA-Z0-9]/g, '')} = ${title.replace(/[^a-zA-Z0-9]/g, '')};
}`;
  }

  enhancedPreview() {
    const code = document.getElementById('code').value.trim();
    if (!this.validateCode(code)) {
      this.setStatus('Bitte korrigiere die Code-Fehler', 'error');
      return;
    }

    this.setStatus('Erstelle Vorschau...', 'info');
    this.startLoading('preview');

    try {
      const startTime = performance.now();
      
      const html = this.createPreviewHTML(code);
      const blob = new Blob([html], {type:'text/html'});
      const iframe = document.getElementById('sandbox');
      
      iframe.onload = () => {
        const endTime = performance.now();
        this.performanceMetrics.previewTime = endTime - startTime;
        this.setStatus('Vorschau aktualisiert', 'success');
        this.recordTestResult('preview', true, `Rendered in ${Math.round(endTime - startTime)}ms`);
        this.stopLoading('preview');
      };
      
      iframe.src = URL.createObjectURL(blob);
      
    } catch (error) {
      this.setStatus('Fehler beim Erstellen der Vorschau: ' + error.message, 'error');
      this.recordTestResult('preview', false, error.message);
      this.stopLoading('preview');
    }
  }

  createPreviewHTML(code) {
    return `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Preview - OAMTM User Studio</title>
  <style>
    body { 
      font-family: system-ui, -apple-system, sans-serif; 
      padding: 20px; 
      background: #0b1020; 
      color: #e5e7eb;
      margin: 0;
    }
    .preview-container { 
      background: #111827; 
      padding: 20px; 
      border-radius: 8px; 
      border: 1px solid #1f2a52;
    }
    .preview-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 16px;
      padding-bottom: 12px;
      border-bottom: 1px solid #1f2a52;
    }
    .preview-title {
      color: #93c5fd;
      margin: 0;
    }
    .preview-status {
      font-size: 0.8em;
      opacity: 0.7;
    }
    .preview-content {
      min-height: 200px;
    }
    .error {
      color: #ef4444;
      background: #1b1433;
      padding: 12px;
      border-radius: 4px;
      border: 1px solid #8b5cf6;
    }
  </style>
</head>
<body>
  <div class="preview-container">
    <div class="preview-header">
      <h3 class="preview-title">Live Preview</h3>
      <span class="preview-status">OAMTM User Studio</span>
    </div>
    <div class="preview-content" id="preview-content">
      <p>Lade Code...</p>
    </div>
  </div>
  <script>
    try {
      ${this.escapeJs(code)}
      document.getElementById('preview-content').innerHTML = '<p>Code erfolgreich ausgeführt!</p>';
    } catch (error) {
      document.getElementById('preview-content').innerHTML = 
        '<div class="error"><strong>Fehler:</strong> ' + error.message + '</div>';
    }
  </script>
</body>
</html>`;
  }

  async enhancedSubmit() {
    const payload = {
      title: document.getElementById('title').value.trim(),
      description: document.getElementById('desc').value.trim(),
      target: document.getElementById('target').value,
      code: document.getElementById('code').value.trim()
    };

    // Validate all fields
    const isValid = this.validateTitle(payload.title) && 
                   this.validateDescription(payload.description) && 
                   this.validateCode(payload.code);

    if (!isValid) {
      this.setStatus('Bitte korrigiere alle Eingabefehler', 'error');
      return;
    }

    this.setStatus('Sende zur Prüfung …', 'info');
    this.startLoading('submit');

    try {
      const startTime = performance.now();
      
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Mock successful submission
      const mockResponse = {
        ok: true,
        pr: Math.floor(Math.random() * 1000) + 1,
        url: `https://github.com/ViewunitySystem/OnAirMulTiMedia/pull/${Math.floor(Math.random() * 1000) + 1}`
      };
      
      const endTime = performance.now();
      this.performanceMetrics.submitTime = endTime - startTime;
      
      if (mockResponse.ok) {
        this.setStatus(`✅ Eingereicht: PR #${mockResponse.pr} - ${mockResponse.url}`, 'success');
        this.recordTestResult('submit', true, `Submitted in ${Math.round(endTime - startTime)}ms`);
        this.resetForm();
      } else {
        this.setStatus(`❌ Fehler: ${mockResponse.error}`, 'error');
        this.recordTestResult('submit', false, mockResponse.error);
      }
      
    } catch (error) {
      this.setStatus('Fehler beim Einreichen: ' + error.message, 'error');
      this.recordTestResult('submit', false, error.message);
    } finally {
      this.stopLoading('submit');
    }
  }

  resetForm() {
    document.getElementById('title').value = '';
    document.getElementById('desc').value = '';
    document.getElementById('code').value = '';
    
    // Clear validation states
    ['title', 'desc', 'code'].forEach(id => {
      const field = document.getElementById(id);
      field?.classList.remove('valid', 'invalid');
      const messageEl = field?.parentNode.querySelector('.validation-message');
      if (messageEl) messageEl.textContent = '';
    });
  }

  startLoading(buttonId) {
    const button = document.getElementById(buttonId);
    if (button) {
      button.disabled = true;
      button.dataset.originalText = button.textContent;
      button.textContent = '...';
    }
  }

  stopLoading(buttonId) {
    const button = document.getElementById(buttonId);
    if (button) {
      button.disabled = false;
      button.textContent = button.dataset.originalText || button.textContent;
    }
  }

  setStatus(text, type = '') {
    const status = document.getElementById('status');
    if (status) {
      status.textContent = text;
      status.className = 'muted';
      if (type === 'success') status.className += ' success';
      if (type === 'error') status.className += ' error';
      if (type === 'info') status.className += ' info';
    }
  }

  startPerformanceMonitoring() {
    // Monitor page load performance
    window.addEventListener('load', () => {
      const perfData = performance.getEntriesByType('navigation')[0];
      this.performanceMetrics.pageLoadTime = perfData.loadEventEnd - perfData.loadEventStart;
      this.recordTestResult('pageLoad', true, `Loaded in ${Math.round(this.performanceMetrics.pageLoadTime)}ms`);
    });
  }

  setupErrorHandling() {
    window.addEventListener('error', (event) => {
      this.recordTestResult('error', false, event.error?.message || 'Unknown error');
    });

    window.addEventListener('unhandledrejection', (event) => {
      this.recordTestResult('promiseRejection', false, event.reason?.message || 'Unhandled promise rejection');
    });
  }

  recordTestResult(testName, success, details) {
    this.testResults.push({
      test: testName,
      success,
      details,
      timestamp: new Date().toISOString()
    });
    
    console.log(`Test ${testName}: ${success ? 'PASS' : 'FAIL'} - ${details}`);
  }

  escapeJs(s) {
    return s.replace(/<\/(script)/gi,'<\\/$1')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
  }

  // Public API for testing
  getTestResults() {
    return this.testResults;
  }

  getPerformanceMetrics() {
    return this.performanceMetrics;
  }

  runFullTestSuite() {
    console.log('Running OAMTM User Studio Test Suite...');
    
    // Test form validation
    this.validateTitle('Test Title');
    this.validateDescription('Test Description');
    this.validateCode('console.log("test");');
    
    // Test AI draft
    this.enhancedAIDraft();
    
    // Test preview
    setTimeout(() => this.enhancedPreview(), 1000);
    
    // Test submit
    setTimeout(() => this.enhancedSubmit(), 2000);
    
    console.log('Test suite completed. Check testResults for details.');
  }
}

// Initialize tester when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
  window.userStudioTester = new UserStudioTester();
  
  // Add test suite to global scope for manual testing
  window.runUserStudioTests = () => {
    window.userStudioTester.runFullTestSuite();
  };
  
  console.log('OAMTM User Studio Tester initialized');
  console.log('Run window.runUserStudioTests() to execute full test suite');
});
